# Generated by Django 4.0.1 on 2023-04-06 13:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pass',
            name='id',
        ),
        migrations.AlterField(
            model_name='pass',
            name='event_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
