# Generated by Django 4.0.1 on 2023-04-06 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_pass_id_alter_pass_event_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_lineup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_lineup', to='api.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_lineup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_lineup', to='api.player'),
        ),
    ]
