# Generated by Django 4.0.1 on 2023-04-20 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_playermatchraport_match_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermatchraport',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.match'),
        ),
        migrations.AlterField(
            model_name='playermatchraport',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.player'),
        ),
    ]
