# Generated by Django 4.0.1 on 2023-04-06 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_lineup_alter_match_away_lineup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineup',
            name='team_id',
        ),
    ]
